name: Deploy Worker

on:
   push:
      branches:
         - main
      paths:
         - "apps/api/**"
         - "packages/api-contract/**"

jobs:
   deploy:
      runs-on: ubuntu-latest
      defaults:
         run:
            working-directory: "./apps/api"
      steps:
         - uses: actions/checkout@v4

         - name: Setup Bun
           uses: oven-sh/setup-bun@v1
           with:
              bun-version: latest

         - name: Install dependencies
           run: bun install

         - name: "Create env file"
           run: |
              touch wrangler.jsonc
              echo '${{ secrets.WRANGLER_JSONC }}' > wrangler.jsonc

         - name: Build & Deploy Worker
           run: bun run deploy
           env:
              CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
